Convert ActiveSupport::SafeBuffer to string
...in Typhoeus::Utils#escape

Otherwise the Regex#last_match is nil and it breaks with
  `NoMethodError: undefined method `bytesize' for nil:NilClass`